name: CI
on:
  pull_request:
defaults:
  run:
    shell: bash

jobs:    
  test:
    strategy:
      fail-fast: false
      matrix:
        test: [jstests, jit-test]
        mozconfig: [ debug, pbl-debug, pbl-release, release, aot-ics-release ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - run: ./mach --no-interactive bootstrap --application-choice=js
    - run: MOZCONFIG=.github/workflows/mozconfig-${{ matrix.mozconfig }} ./mach build
    - run: MOZCONFIG=.github/workflows/mozconfig-${{ matrix.mozconfig }} ./mach ${{ matrix.test }}
